### ISSUE TITLE
Cannot activate "YouTube Field Colorbox" submodule

### ISSUE THREAD

**Issue by sternhagel** [backdrop-contrib/youtube#20] opened 2019-11-28 14:35 UTC
When trying to activate "YouTube Field Colorbox" submodule, the system shows the following error:

> ParseError: syntax error, unexpected '$domain' (T_VARIABLE) in backdrop_load() (line 165 in [...]/modules/youtube/modules/youtube_colorbox/youtube_colorbox.module).

**Comment by olafgrabienski** [comment] 2019-11-28 17:44
This seems to be a duplicate of https://github.com/backdrop-contrib/youtube/issues/20.

@jenlampton Are you up to make a new release which contains the fix for #20?

**Closed as completed by olafgrabienski** 2019-11-28 17:44 UTC
Labels: duplicate
