### ISSUE TITLE
Page with YouTube field not editable, date() TypeError

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/youtube#45] opened 2023-12-14 14:03 UTC
After updating the module to version `1.x-1.1.1`, I can't edit some pages with a YouTube field. Instead, I get a blank page with the error "date(): Argument #2 ($timestamp) must be of type ?int, string given". In DBlog I see the following message:

TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in date() (line 607 of (...)/modules/youtube/youtube.module).

**Comment by olafgrabienski** [comment] 2023-12-14 14:07
I guess the issue might have been introduced by the start time feature.

**Comment by yorkshire-pudding** [comment] 2023-12-14 14:49
Hi @olafgrabienski - I don't suppose you know what the URL is for that video?  I have an idea how to fix this, but it would be helpful to understand better the conditions causing this, so I can be sure it has fixed it.

Is there a URL with `t=sometext` rather than `t=120` or another number?

**Comment by yorkshire-pudding** [comment] 2023-12-14 15:01
Ok @olafgrabienski - managed to reproduce by adding the query `t=wibble`

Please can you test the pull request.

**Comment by olafgrabienski** [comment] 2023-12-14 15:29
@yorkshire-pudding Thanks for the quick response! You're right, as I'm not able to edit the node, I can't see the URL in the YouTube field. When I inspect the code with Developer tools, I see the following URL:

`https://www.youtube-nocookie.com/embed/d5yxE0Qu2Dw?rel=0&modestbranding=1&wmode=opaque&start=1s`

Wondering about the `start=1s` part. Not sure if the editors put it there, or if it was added by the module.

On a dev version of the site there is no issue. On that page, the URL in the YouTube field of the page is the following:

`https://www.youtube.com/watch?v=d5yxE0Qu2Dw`

It's the same video, so again I'm wondering where the `start=1s` on the live site is coming from.

In case it's of interest: The sites have different PHP versions. Dev 8.1.14, Live 8.1.26

**Comment by yorkshire-pudding** [comment] 2023-12-14 15:44
Interesting. I presume that is the URL on viewing the page, which is generated depending on module and display mode settings. When you apply the diff from the PR, can you now see the URL saved in the node?
The module is only looking for the `t` query parameter which would either look like `?t=120` or `?anotherparameter=wibble&t=120`

**Comment by olafgrabienski** [comment] 2023-12-14 16:19
@yorkshire-pudding Thanks for the PR! After applying it to the site, I was able to edit the page and to see the URL. So, the PR works for me.

For the record, there was indeed a `t` query in the URL:

`https://www.youtube.com/watch?v=MY-VIDEO-ID&t=1s`

I guess, the tiny `s` for seconds lead to the not valid URL format.

**Comment by argiepiano** [comment] 2023-12-14 16:23
I believe the "s" is a syntax error. Did this appear from "Share" in the youtube site? OR was this URL taken from another place (which may have contained that error).

Still, the idea of using a "failsafe" as in the PR is good.

**Comment by argiepiano** [comment] 2023-12-14 16:27
Wait, Youtube adds the "s" once you paste a link that has a starting time. In this snapshot, my link did not contain an "s" - but youtube added it. 

So, it seems like your link @olafgrabienski came from copying the URL from the browser bar, and it contained the "s". This seems to be new. I think we should account for those "s" being added - perhaps trim it? @yorkshire-pudding?

<img width="790" alt="Screen Shot 2023-12-14 at 9 25 28 AM" src="https://github.com/backdrop-contrib/youtube/assets/9938978/2d8ab6d4-caf7-4457-85c1-fa40bab5af99">

**Comment by yorkshire-pudding** [comment] 2023-12-14 17:20
@argiepiano @olafgrabienski 

Thanks for feedback.

Now, if it says `t=120s` with will set the start time as 29 seconds. If it says `t=wibbles` time will be set to 0.

Grateful for any further feedback.

**Comment by argiepiano** [comment] 2023-12-14 17:28
Unfortunately, it looks like the syntax also allows for "m" and "h", which get transformed into the "s" notation. Try the following:

https://www.youtube.com/watch?v=d9VtzVRaz6Q&t=5m

https://www.youtube.com/watch?v=d9VtzVRaz6Q&t=1h

So, do we account for those as well?

**Comment by yorkshire-pudding** [comment] 2023-12-14 17:40
Hmm. I'm not sure what the best thing to do here is. We could pass them through and ditch the feedback on the edit page that shows a user friendly start time.  I'm afraid my regex skills are not up to working out how to parse all the different combinations to account for possibilities.  I guess we might also have `t=2h5m20s`

Any thoughts?

**Comment by argiepiano** [comment] 2023-12-14 20:24
> We could pass them through and ditch the feedback on the edit page that shows a user friendly start time

I think that may be the best way to go. Just output the string after `t=` verbatim. 

I did notice that the user friendly start time is showing the wrong time for a video test:

<img width="1193" alt="Screen Shot 2023-12-14 at 1 22 55 PM" src="https://github.com/backdrop-contrib/youtube/assets/9938978/dec71b7f-f69f-4112-b9e7-c5a22ba2cc8d">

**Comment by argiepiano** [comment] 2023-12-14 20:46
Otherwise, if we know that the syntax is always going to be 1h2m10s (or a combination such as   2m10s or 1h20s etc), then we could use:

```php
$matches = array();
preg_match("/(\d*)h|(\d*)m|(\d*)s/", '1m12s', $matches, PREG_UNMATCHED_AS_NULL);
```
where `$matches[1]` will be hours (or null), 2 will be minutes or null and 3 will be seconds or null. 

This check needs to be done only if the parameter is a string - if it's a number, then it's seconds.

[EDIT] Actually the regex expression above doesn't quite work for the example. I'll keep digging.

**Comment by yorkshire-pudding** [comment] 2023-12-15 09:36
I tried passing through the string. It works for `t=29` but not `t=29s`
This is because the embed specification is more restrictive than what Youtube does elsewhere:
https://support.google.com/youtube/answer/171780?hl=en-GB#zippy=%2Cstart-an-embedded-video-at-a-certain-time

I need to fix this fatal error so I'm minded to strip out anything that isn't an integer for now ~~, and strip out the user-friendly time.~~

In my testing, other than for 0 (which I now hide), the user friendly time worked fine. I wonder whether you changed the `t=` to 112 just before taking the screenshot? It does not update in real time, only on page load.

Any clever regex that handles the different cases can follow up later.

**Comment by yorkshire-pudding** [comment] 2023-12-15 12:09
@olafgrabienski @argiepiano 
The priority for this ticket has to be fixing the fatal error that Olaf experienced.

I've added an explanation about when start time (and ID) is updated. I am now discarding anything in the `t` query parameter that isn't a pure number.

Any future addition that handles `t` strings with `h`, `m` and/or `s` will need to convert to seconds to work with the embed function.

If there are scenarios where the user friendly start time does not reflect the number of seconds **after the node is saved**, please provide reproducible steps.  It would be nice to update via ajax but I don't have time to figure this out at the moment.

**Comment by argiepiano** [comment] 2023-12-15 13:46
> In my testing, other than for 0 (which I now hide), the user friendly time worked fine. I wonder whether you changed the t= to 112 just before taking the screenshot? It does not update in real time, only on page load.

No, this was the value in the field. I'm ok leaving this inconsistency for a different issue.

As for regex you can try:

```php
$minutes = $seconds = $hours = array();
$string = '12h10s';
preg_match("/(\d*)s/", $string, $seconds);
preg_match("/(\d*)m/", $string, $minutes);
preg_match("/(\d*)h/", $string, $hours);
$seconds = !empty($seconds[1]) ? $seconds[1] : '';
$minutes = !empty($minutes[1]) ? $minutes[1] : '';
$hours = !empty($hours[1]) ? $hours[1] : '';
dpm($seconds);
dpm($minutes);
dpm($hours);
```
 
Not the most efficient, but it works. I'm sure there must be better ways...

**Comment by yorkshire-pudding** [comment] 2023-12-15 14:13
Thanks @argiepiano 
I've added that in.  Seems to work with any combination.

**Comment by yorkshire-pudding** [comment] 2023-12-15 14:31
@argiepiano also fixed #47 in this PR as it was a 2 letter change.

**Comment by olafgrabienski** [comment] 2023-12-15 14:43
> The priority for this ticket has to be fixing the fatal error that Olaf experienced.

Thank you again @yorkshire-pudding. I've tested the current PR, and it still fixes the issue. I've also tested the new options, specifying hours, minutes and seconds. They all work for me, very nice!

**Comment by yorkshire-pudding** [comment] 2023-12-15 17:05
Thanks for the suggestions @argiepiano and @olafgrabienski - hopefully can get this merged and released before it becomes a problem for anyone else.

**Comment by argiepiano** [comment] 2023-12-15 17:10
LGTM!

**Closed as completed** 2023-12-15 17:14 UTC
